name: flutter_email_app
description: Email Sender - Send personalized emails with glassmorphic UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  crypto: ^3.0.7
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  file_picker: ^6.1.1
  fl_chart: ^0.66.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
